image: ubuntu:22.04

stages:
  - package
  - deploy

package_charts:
  stage: package
  before_script: 
    - apt-get update -y && apt-get install -y curl tar git
    - curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
    - chmod 700 get_helm.sh
    - ./get_helm.sh
    - git fetch origin "gl-pages"
    - git remote set-url origin https://${GITLAB_USER_NAME}:${GITLAB_CI_TOKEN}@${CI_REPOSITORY_URL}
  script:
    - git checkout gl-pages
    - git checkout remotes/origin/development -- charts scripts .gitignore README.md
    - cd charts
    - ../scripts/process-charts.sh
    - cd ..
    - rm -r charts scripts
    - helm repo index --url ${CI_PAGES_URL} ./public
    - git config --global user.email "${GITLAB_USER_EMAIL}"
    - git config --global user.name "${GITLAB_USER_NAME}"
    - git add .
    - git commit -m "Publish Helm charts and additional files"
    - git push origin gl-pages
  rules:
    - if: $CI_COMMIT_BRANCH == "development"

pages:
  stage: deploy
  script:
    - echo "Pages accessible through ${CI_PAGES_URL}"
  pages:
    path_prefix: "$PAGES_PREFIX"
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_BRANCH == "gl-pages"