apiVersion: v2
name: api360
description: A Helm chart for Kubernetes
type: application
version: 0.1.1
appVersion: "12"
dependencies:
  - name: mysql
    version: 10.1.*
    repository: https://charts.bitnami.com/bitnami
    condition: mysql.enabled