apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: {{ .Values.mysql.image }}
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: api360-mysql
              mountPath: /var/lib/mysql
      volumes:
        - name: api360-mysql
          {{- if .Values.mysql.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ if .Values.mysql.persistence.existingClaim }}{{ .Values.mysql.persistence.existingClaim }}{{- else }}{{ template "api360.fullname" . }}-mysql{{- end }}
          {{- end }}