apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api360.fullname" . }}-app
type: Opaque
data:
  jwt-passphrase: {{ .Values.secrets.jwtPassphrase | b64enc | quote }}
  app-secret: {{ .Values.secrets.appSecret | b64enc | quote }}
